---
- name: Deploy Healthcare App to Kubernetes
  hosts: local
  gather_facts: false
  vars:
    project_dir: "{{ lookup('env', 'WORKSPACE') | default('/home/udit/2ndSem/SPEProject', true) }}"
    kubeconfig_path: "/home/udit/2ndSem/SPEProject/kubeconfig"
  tasks:
    - name: Apply MySQL Deployment
      command: "kubectl apply -f k8s/mysql-deployment.yaml --kubeconfig={{ kubeconfig_path }}"
      args:
        chdir: "{{ project_dir }}"

    - name: Apply Backend Deployment
      command: "kubectl apply -f k8s/deployment.yaml --kubeconfig={{ kubeconfig_path }}"
      args:
        chdir: "{{ project_dir }}"

    - name: Apply Services
      command: "kubectl apply -f k8s/service.yaml --kubeconfig={{ kubeconfig_path }}"
      args:
        chdir: "{{ project_dir }}"

    - name: Apply Frontend Deployment
      command: "kubectl apply -f k8s/frontend-deployment.yaml --kubeconfig={{ kubeconfig_path }}"
      args:
        chdir: "{{ project_dir }}"
