input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [app_name] == "healthcare-backend" {
    mutate {
      add_field => { "application" => "healthcare" }
    }
  }

  if [level] == "WARN" or [level] == "ERROR" {
    mutate {
      add_tag => ["security_alert"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "healthcare-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
